# Generated by Django 5.2.7 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
