# Generated by Django 5.2.7 on 2025-10-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_logo'),
        ('tournaments', '0002_alter_tournament_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='teams.team'),
        ),
    ]
