# Generated by Django 5.2.7 on 2025-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PENYELENGGARA', 'Penyelenggara'), ('PEMAIN', 'Pemain')], default='PEMAIN', max_length=20),
        ),
    ]
