# Generated by Django 5.2.7 on 2025-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PENYELENGGARA', 'Penyelenggara'), ('PEMAIN', 'Pemain')], default='PEMAIN', max_length=20),
        ),
    ]
